apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train-service
  name: train-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-service
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: train-service
    spec:
      containers:
      - image: renukafernando/train-service:0.2.3 # Old Image (just break to MS) renukafernando/train-service:0.1.3
        imagePullPolicy: IfNotPresent
        name: train-service
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: train-service
  name: train-service
spec:
  ports:
    - name: http-bin
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: train-service
  type: ClusterIP
